version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: database
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: Password
        networks:
            - bookstore
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - bookstore

networks:
    bookstore:
        driver: bridge